---
- name: Block a malicious IP using iptables
  hosts: all
  become: yes
  vars:
    target_ip: "192.168.1.11"

  tasks:
    - name: Block IP using iptables (only if not already blocked)
      ansible.builtin.shell: >
        /usr/sbin/iptables -C INPUT -s {{ target_ip }} -j DROP ||
        /usr/sbin/iptables -A INPUT -s {{ target_ip }} -j DROP
      args:
        warn: false

    - name: Save iptables rules (Debian/Ubuntu)
      ansible.builtin.shell: >
        /usr/sbin/iptables-save > /etc/iptables/rules.v4
      when: ansible_os_family == "Debian"
      ignore_errors: yes
