
---
- name: Block a malicious IP using iptables
  hosts: all
  become: yes
  vars:
    target_ip: "192.168.1.11"  # Mặc định, có thể override bằng Survey hoặc Extra Vars

  tasks:
    - name: Block IP using iptables (only if not already blocked)
      ansible.builtin.shell: >
        iptables -C INPUT -s {{ target_ip }} -j DROP ||
        iptables -A INPUT -s {{ target_ip }} -j DROP
      args:
        warn: false

    - name: Save iptables rules (Debian/Ubuntu)
      ansible.builtin.shell: iptables-save > /etc/iptables/rules.v4
      when: ansible_os_family == "Debian"
      ignore_errors: yes  # Nếu chưa cài iptables-persistent
