---
- name: Block an IP using iptables (INPUT and DOCKER-USER)
  hosts: localhost
  become: true
  gather_facts: true

  tasks:
    - name: Ensure iptables is installed
      package:
        name: iptables
        state: present
      delegate_to: 127.0.0.1

    - name: Check if IP is already blocked in INPUT
      shell: iptables -C INPUT -s 1.2.3.4 -j DROP
      register: check_input
      ignore_errors: true
      delegate_to: 127.0.0.1

    - name: Block IP in INPUT chain if not already present
      shell: iptables -A INPUT -s 1.2.3.4 -j DROP
      when: check_input.rc != 0
      delegate_to: 127.0.0.1
