---
- name: Block a malicious IP using iptables
  hosts: all
  become: yes
  vars:
    target_ip: "192.168.1.11"

  tasks:
    - name: Debug PATH used by Ansible
      ansible.builtin.debug:
        var: ansible_env.PATH

    - name: Block IP using iptables (explicit full path)
      ansible.builtin.command: >
        /usr/sbin/iptables -C INPUT -s {{ target_ip }} -j DROP
      register: check_rule
      failed_when: false

    - name: Append IP block rule if not present
      ansible.builtin.command: >
        /usr/sbin/iptables -A INPUT -s {{ target_ip }} -j DROP
      when: check_rule.rc != 0

    - name: Save iptables rules (Debian/Ubuntu)
      ansible.builtin.command: >
        /usr/sbin/iptables-save
      register: iptables_rules

    - name: Write rules to /etc/iptables/rules.v4
      ansible.builtin.copy:
        content: "{{ iptables_rules.stdout }}"
        dest: /etc/iptables/rules.v4
      when: ansible_os_family == "Debian"
      ignore_errors: yes


