- name: Block a malicious IP using iptables
  hosts: localhost
  become: yes
  tasks:
    - name: Kiểm tra rule đã tồn tại chưa
      ansible.builtin.command: /usr/sbin/iptables -C INPUT -s 1.1.1.1 -j DROP
      register: iptables_check
      ignore_errors: yes

    - name: Thêm rule nếu chưa tồn tại
      ansible.builtin.command: /usr/sbin/iptables -A INPUT -s 1.1.1.1 -j DROP
      when: iptables_check.rc != 0


